// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXYDkBwTkH93DOLCGqndtTC5us4fnlzU',
    appId: '1:995507730731:web:1d8d0e5e8b8aca94852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    authDomain: 'servicemanagement-saas.firebaseapp.com',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    measurementId: 'G-0KPSYE9DP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgK8yrD0fjUuHTULzbdVrMfkqRDdl9hFU',
    appId: '1:995507730731:android:b38df643cc6ca875852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUDXEfVhRNPj10jqPReeNz4Mc63edSAs',
    appId: '1:995507730731:ios:35e2f6896bf9b237852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    iosBundleId: 'com.example.serviceManagementSoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUDXEfVhRNPj10jqPReeNz4Mc63edSAs',
    appId: '1:995507730731:ios:35e2f6896bf9b237852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    iosBundleId: 'com.example.serviceManagementSoftware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdXYDkBwTkH93DOLCGqndtTC5us4fnlzU',
    appId: '1:995507730731:web:34d0a9a6c94c76cf852d6e',
    messagingSenderId: '995507730731',
    projectId: 'servicemanagement-saas',
    authDomain: 'servicemanagement-saas.firebaseapp.com',
    storageBucket: 'servicemanagement-saas.firebasestorage.app',
    measurementId: 'G-36NLRD18B6',
  );
}
